-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  tenants

CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NOT NULL,
  slug_ci TEXT GENERATED ALWAYS AS (lower(slug)) STORED,
  status TEXT NOT NULL DEFAULT 'active',              -- 'active','suspended','deleted'
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_tenants_status CHECK (status IN ('active','suspended','deleted')),
  deleted_at TIMESTAMPTZ(6) NULL,
  is_live BOOLEAN GENERATED ALWAYS AS (deleted_at IS NULL) STORED
);
